# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
---
- hosts: all
  gather_facts: false

  tasks:
  - raw: which python || apt-get update
  
  - raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude
  
  - name: Create data directory for mongoDB /data/db
    file: path=/data/db

  - name: Create temp primary.js script
    raw: echo "cfg = rs.conf()\n
         cfg.members[0].priority = 0.5\n
         cfg.members[1].priority = 0.5\n
         cfg.members[2].priority = 1\n
         cfg.members[3].priority = 0.4\n
         rs.reconfig(cfg)" > /tmp/primary.js

#- hosts: primary
#  gather_facts: false
#
#  tasks:
#  - raw: echo "test" > /tmp/test.asc
