# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
---
- hosts: all
  gather_facts: false

  tasks:
  - raw: which python || apt-get update
  - raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude
  #- name: Install python
  #  package: name=python3 state=latest use=apt
  #- name: Install python
  #  raw: apt-get install -y python 
  - name: Create data directory for mongoDB
    file: path=/data/db
